GET http://localhost:5000/

###

POST http://localhost:5000/sign_up
Content-Type: application/json

{
    "user":"u5",
    "pass":"Password"
}

###
GET http://localhost:5000/login
Content-Type: application/json

{
    "user":"Akassh",
    "pass":"Password"
}

###

GET http://localhost:5000/logout
Content-Type: application/json

{
    "user":"Akassh"
}
###
GET http://localhost:5000/users
