GET http://localhost:5000/



###
POST http://localhost:5000/sign_up
Content-Type: application/json

{
    "name":"AkashBansal",
    "email":"email@anymail.com",
    "user":"username",
    "pass":"Password"
}




###
GET http://localhost:5000/login
Content-Type: application/json

{
    "user":"username",
    "pass":"Password"
}


###
GET http://localhost:5000/checkStatus
Content-Type: application/json

{
    "sessid" : "afd1292a38e965e99726518sc26fd76e1c04fa6fe77ad2f96f4"
}


###
GET http://localhost:5000/logout
Content-Type: application/json

{
    "user":"username",
    "sessID":"a0d57934006997664ef795b1c915d761dc3861d35d10b5188c"
}




###
GET http://localhost:5000/users
Content-Type: application/json

{
    "secret_key":"__SEC_RET__KE_Y"
}


###
GET http://localhost:5000/delete
Content-Type: application/json

{
    "user":"username1",
    "pass":"Password"
}