GET http://localhost:5000/



###
POST http://localhost:5000/sign_up
Content-Type: application/json

{
    "name":"AkashBansal",
    "email":"email@anymail.com",
    "user":"username",
    "pass":"Password"
}




###
GET http://localhost:5000/login
Content-Type: application/json

{
    "user":"username",
    "pass":"Password"
}



###
GET http://localhost:5000/logout
Content-Type: application/json

{
    "user":"username"
}




###
GET http://localhost:5000/users


###
GET http://localhost:5000/delete
Content-Type: application/json

{
    "user":"username",
    "pass":"Password"
}